### ISSUE TITLE
Keyboard shortcuts for review sessions

### ISSUE THREAD

**Issue by andymatuschak** [andymatuschak/orbit#165]
We should have keyboard shortcuts for "reveal", "remembered", and "forgotten." 

These should be (at least relatively) resilient to a) changes to the "remembered" / "forgotten" label wording; b) adding a third or fourth action.

It should probably be possible to access all keyboard shortcuts one-handed.

We should probably display some affordance in the UI (only if a physical keyboard is present) to hint the key. No strong feelings at this moment: we could start with a tooltip or a hover element.

**Comment by growthepie** [comment]
I can work on this!

I was thinking <kbd>Space</kbd> for both *reveal* & *remembered* and <kbd>F</kbd> for *forgotten*. Reasons:
- Fast review process: most common action is *reveal* -> *remembered*, which would mean double spaces
- One-handed: only requires left thumb and index finger
- Even if *forgotten* will be changed to something else, <kbd>F</kbd> is still relevant because of the [Press F to Pay Respects](https://knowyourmeme.com/memes/press-f-to-pay-respects) meme

Should this be implemented in the `@withorbit/ui` package or in the `@withorbit/app`?

**Comment by andymatuschak** [comment]
Thank you for offering, @growthepie!

One interesting consideration here: in the future, I'd like Orbit to support microtasks other than memory prompts, which might have different feedback buttons. For instance, a lightweight exercise ("improvise a melody in pentatonic minor") might have similar buttons with different titles ("went well" / "needs more practice"). A gratitude activity ("visualize the surprise party your friends threw you") might have three buttons ("repeat with same interval", "see more often", "see less often").

It'd be neat to choose keyboard shortcuts which could "grow" in this way. It's probably reasonable to assume that the buttons will continue to be arranged in a sequence (e.g. in a row) and that there's (often) a default button.

Given that, how about `space` for "reveal" and "default action" (i.e. "remembered"), and then `1` / `2` for "forgotten" / "remembered" respectively? Still one-handed, which is nice.

**Comment by andymatuschak** [comment]
(Oh, regarding where to implement: I'd suggest `ReviewArea.tsx`!)

**Comment by growthepie** [comment]
Great — I love the idea of microtasks! Sometimes my prompts consist of just a link to a Khan Academy unit test. Maybe those could be considered microtasks as well and could use custom actions.

> It'd be neat to choose keyboard shortcuts which could "grow" in this way.

Totally agree, let's do it this way! Will work on a PR.
