### ISSUE TITLE
Project: add validation for core data types (API, storage)

### ISSUE THREAD

**Issue by andymatuschak** [andymatuschak/orbit#184]
I've played fast and loose with validation in Orbit so far, but particularly as we use on-device storage and open up a public API, we need to get serious about this. We need validators for all our core data types. When both client and server receive data from the network, they must validate that request/response. When reading data from disk, we should validate that data.

Ideally, our validation strategy is fairly automatic: either we're automatically generating code based on our TS types, or we're using some strategy to infer a validator at runtime (e.g. like [io-ts](https://github.com/gcanti/io-ts)).

I'd love help evaluating the approaches we might take to this, making a call, implementing the infrastructure, and adopting it appropriately throughout the system.

**Comment by kirkbyo** [comment]
Gotcha, thanks for shining some light on the additional scope of this problem. I was overlooking the canonicalization routines. In that case, I am currently thinking of breaking down the tasks into the following PR's:

1. Set up validation at the HTTP layer on both the client and the backend. Since the `api` types consume a lot of the `core` types, this will be a little tricky. For this first PR, the API surface will be fully defined using JSON schemas however the definition of the core types will be duplicated. I won't convert the core types to be JSON schema's just yet to limit the blast radius. From here, I will set up `ajv` and `json-schema-to-typescript` and add a Github action to ensure that the Codegen has run before any merges. I hope this will expose any initial "gotcha's and allow us to pivot before investing too much.
2. Convert the `core` types to be JSON schema's instead and replace the canonicalization with `ajv`. I will remove the duplication introduced in the first PR, and instead reference the `core` types from the `API` schemas. 
3. Validate local serialization? I'll admit, I am not quite sure what you mean by "local serializations". Regardless, we can loop back at this point to see where else validation is needed.

Let me know if you have any other ideas or reservations about this approach!

**Comment by andymatuschak** [comment]
Got it, sounds reasonable!

Regarding the local serialization: I mean loading from a local LevelDB database (a few implementations in `app`). But actually, it probably makes sense to hold off on that part, since I'm going to be substantially rearchitecting it in the coming weeks (or so I keep saying!).
