### ISSUE TITLE
Build and Run of web app failed

### ISSUE THREAD

**Issue by dgdosen** [andymatuschak/orbit#229]
(Please read the "Contributing" section of the project README before continuing.)

**Describe the bug**
I downloaded the project, and followed the readme(s):
- ran yarn install & yarn build in the monorepo root (no issues)
- ran yarn install  & yarn build & yarn dev in the backend (no issues)
- ran yarn install & yarn build & yarn run web in the app (issue)

Running in this mode , I could see three browser tabs for:
- Firebase Emulator
- Metro Bundler 
(Both seem to be running)
- orbit web page:
-- error 
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

**To Reproduce**

See the description above - starting from 'scratch' 
I was using node 14.17.3 (LTS)

**Expected behavior**
Orbit running!

**Screenshots**
![orbit_error](https://user-images.githubusercontent.com/75257/126912338-3962fe0d-0b45-4ca8-9605-404580a262bc.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser Chrome
 - Version: 92.0.4515.107

Is there a version of react/react-hooks that should be used for the app?  Might there be breaking changes when installing and pulling what might be newer versions of react?

**Comment by andymatuschak** [comment]
Sorry for the trouble, @dgdosen. The dangers of the Node ecosystem: two different dependencies were depending on different versions of React. And the problem happened not to manifest on my system because of stale `node_modules`. One more reason to make integration testing happen, I suppose (cc @kirkbyo).

This should be fixed now. If the problem persists, you may need to delete `node_modules` in both the root directory of the project and in `packages/app`; and you may need to run `yarn web -c` to clear the bundler's caches.
